version: '3'
services:
  app:
    build: .
    env_file: develop.env
    ports:
      - '8000:80'
    platform: linux/amd64
    secrets:
      - gcp-credentials
secrets:
  gcp-credentials:
    file: ./gcp-creds.json